### ISSUE TITLE
Doesn't work on MacOS 10.15.5

### ISSUE THREAD

**Issue by jdeibele** [ildella/pocket-cli#170]
Pocket CLI - darwin
Pocket> login
\/bin/sh: undefined: command not found
Error: Command failed: undefined "https://getpocket.com/auth/authorize?request_token=9147f44d-1de1-86d6-bd51-3d1dda&redirect_uri=http://localhost:3300/oauth/pocket/callback"
/bin/sh: undefined: command not found

    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at Object.pocketAuth.login (/usr/local/lib/node_modules/pocket-cli/src/pocket/pocket-auth.js:21:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.execute (/usr/local/lib/node_modules/pocket-cli/src/pocket/pocket-parse.js:31:9)
    at async Object.processInput (/usr/local/lib/node_modules/pocket-cli/src/cli/process-input.js:27:23) {
  status: 127,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 2f 62 69 6e 2f 73 68 3a 20 75 6e 64 65 66 69 6e 65 64 3a 20 63 6f 6d 6d 61 6e 64 20 6e 6f 74 20 66 6f 75 6e 64 0a>
  ],
  pid: 37141,
  stdout: <Buffer >,
  stderr: <Buffer 2f 62 69 6e 2f 73 68 3a 20 75 6e 64 65 66 69 6e 65 64 3a 20 63 6f 6d 6d 61 6e 64 20 6e 6f 74 20 66 6f 75 6e 64 0a>
}
big error: Error
Pocket>

**Comment by ildella** [comment]
I've found the problem and committed a fix: https://github.com/ildella/pocket-cli/commit/25982726411083f00085ef4116f4e205a9eb15d9

As soon as I manage to make a new release, you'll be able to try it.

**Comment by ildella** [comment]
@jdeibele version 0.8.3 is released and contains a change that should fix this issue.

**Comment by jdeibele** [comment]
It's working properly with the new version.   Thank you!
